# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
