# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20170802_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='level',
            field=models.IntegerField(default=3),
        ),
    ]
